FROM krustylebot/repo:sdci
WORKDIR /
ADD . /
RUN echo ‘nameserver 8.8.8.8’ >> /etc/resolve.conf && echo ‘nameserver 8.8.4.4’ >> /etc/resolve.conf’ \

ENTRYPOINT  cd Projet-SDCI; git pull; node LeakyBucket/leakybucket.js; tail -f /dev/null