FROM node:alpine
WORKDIR /
ADD . /
RUN apk update && apk add \
	net-tools \
    iputils-ping \
	iproute2 \
    nodejs \
    npm \
    git \
    && npm install express \
    && npm install request \
    && wget http://homepages.laas.fr/smedjiah/tmp/server.js \
    && wget http://homepages.laas.fr/smedjiah/tmp/gateway.js \
    && wget http://homepages.laas.fr/smedjiah/tmp/device.js \
    && git clone https://github.com/KrustyLeBot/Projet-SDCI.git \

CMD /bin/bash