FROM ubuntu:trusty
WORKDIR /
ADD . /
RUN sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys E1DD270288B4E6030699E45FA1715D88E1DF1F24 \
    && sudo su -c "echo 'deb http://ppa.launchpad.net/git-core/ppa/ubuntu trusty main' > /etc/apt/sources.list.d/git.list" \
    && apt-get update && apt-get install -y \
	net-tools \
    iputils-ping \
	iproute \
	git \
    npm \
    nodejs \
    && npm install express \
    && npm install request \
    && wget http://homepages.laas.fr/smedjiah/tmp/server.js \
    && wget http://homepages.laas.fr/smedjiah/tmp/gateway.js \
    && wget http://homepages.laas.fr/smedjiah/tmp/device.js \
    && git clone https://github.com/KrustyLeBot/Projet-SDCI.git \

CMD /bin/bash