FROM krustylebot/repo:sdci_python

RUN	echo ‘nameserver 8.8.8.8’ >> /etc/resolve.conf && echo ‘nameserver 8.8.4.4’ >> /etc/resolve.conf’

# set entry point for emulator gatekeeper
ENV VIM_EMU_CMD "cd /Projet-SDCI/VNF; git pull; python3 master_vnf.py; echo 'End VNF start'"
ENV VIM_EMU_CMD_STOP "echo 'Stopping the container now.'"

# CMD should always point to /bin/bash to not block the emulator
CMD ["sh"]