FROM krustylebot/repo:sdci

RUN	echo ‘nameserver 8.8.8.8’ >> /etc/resolve.conf && echo ‘nameserver 8.8.4.4’ >> /etc/resolve.conf’

# set entry point for emulator gatekeeper
ENV VIM_EMU_CMD "echo 'Start virtual GW start'; cd /Projet-SDCI/docker; git pull; sh script_gi.sh 10.0.0.11 10.0.0.10 gwi1; echo 'End virtual GW start'; tail -f /dev/null'"
ENV VIM_EMU_CMD_STOP "echo 'Stopping the container now.'"

# CMD should always point to /bin/bash to not block the emulator
CMD ["sh"]